# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Site Infomation
site_name: Zhazi's Memo
site_description: A personal knowledge base for storing notes, research, and technical documentation
site_author: Zhazi
repo_name: Memo
repo_url: https://github.com/the-full/the-full.github.io


theme:
  name: material
  language: zh
  font: false
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换至浅色模式
  # include_search_page: false # NOTE: 东西多了以后在开启
  # search_index_only: true
  features:
    - content.action.edit
    # - content.action.tabs # NOTE: 需要配合 nav 使用
    - content.action.view
    - content.code.copy
    - content.tooltips
    # - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'


plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Reading    # 读点新东西 (带有理解) => !!! 导言[必选] + ??? 文献信息
        - Learning   # 学点新东西 (带有实践) => !!! 导言[可选] + ??? 参考文献
        - Summary    # 总结知识 (带有系统化的知识) => 导言 + 参考文献
        - Memo       # 备忘录 (搬运的内容，将分散的知识集中化) 
        - Misc       # 杂项，不知道该归类为哪种 => 自由设置
      pagination_per_page: 5
      draft: false
  - tags
  - glightbox


markdown_extensions:
  - tables
  - abbr
  - admonition
  - footnotes
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

watch:
  - includes

extra:
  social:
    - icon: fontawesome/brands/github
      name: zhazi on github
      link: https://github.com/the-full
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'

extra_css:
  - _static/css/extra.css


extra_javascript:
  - _static/js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Blog:
    - blog/index.md
